// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String meddelande;
int sensorVarde;
CloudPercentage fuktProcent;

void initProperties(){

  ArduinoCloud.addProperty(meddelande, READ, ON_CHANGE, NULL, 60);
  ArduinoCloud.addProperty(sensorVarde, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(fuktProcent, READ, 60 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
